version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Setting up Docker..."
      - docker --version
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 47XXXXXXXXXXXXXXXXXXXX9.dkr.ecr.us-east-1.amazonaws.com

  pre_build:
    commands:
      - echo "Checking Maven version..."
      - mvn --version

  build:
    commands:
      - echo "Building the Spring Boot application..."
      - mvn clean install
      - echo "Building Docker image..."
      - docker build -t devclass1/repo1 .
      - docker tag devclass1/repo1:latest 47XXXXXXXXXXXXXXXXXXXXXXXXX29.dkr.ecr.us-east-1.amazonaws.com/devclass1/repo1:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 47XXXXXXXXXXXXXXXXXX9.dkr.ecr.us-east-1.amazonaws.com/devclass1/repo1:latest
      - echo "Build and push completed successfully!"

artifacts:
  files:
    - target/*.jar
